version: "3.5"

services:
  php:
    build:
      context: php
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/my-custom-php.ini

  mysqldb:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 10000:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: root
